name: alienbattle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.2.1
  flame_forge2d: ^0.12.1
  vibration: ^1.7.6
  uuid: ^3.0.6
  realtime_client:
    path: ../realtime-dart

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
